server.port: 8081 
  
#config spring data-jpa
spring:
  main:
    allow-circular-references: true
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
    properties.hibernate.dialect: org.hibernate.dialect.MySQL55Dialect
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/phonestore
    username: root
    password: 
    


